CREATE TABLE IF NOT EXISTS `mediaserver`.`viewed` ( `ID` INT NOT NULL AUTO_INCREMENT , `COURSE` VARCHAR(256) NOT NULL , `TOPIC` VARCHAR(256) NOT NULL , `LECTURE` VARCHAR(256) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mediaserver`.`completed` ( `ID` INT NOT NULL AUTO_INCREMENT , `COURSE` VARCHAR(256) NOT NULL , `TOPIC` VARCHAR(256) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mediaserver`.`notes` ( `ID` INT NOT NULL AUTO_INCREMENT , `COURSE` VARCHAR(256) NOT NULL , `TOPIC` VARCHAR(256) NOT NULL , `LECTURE` VARCHAR(256) NOT NULL , `TIME` VARCHAR(256) NOT NULL , `NOTE` VARCHAR(1000) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mediaserver`.`unfinished` ( `ID` INT NOT NULL AUTO_INCREMENT , `COURSE` VARCHAR(256) NOT NULL , `TOPIC` VARCHAR(256) NOT NULL , `LECTURE` VARCHAR(256) NOT NULL , `TIME` VARCHAR(256) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;